// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhiSUdWa81y8XuTsauGDYS-Ns4OluBWGo',
    appId: '1:383875206920:android:b8da0e14ef8311233166bd',
    messagingSenderId: '383875206920',
    projectId: 'hazelnut-messenger',
    storageBucket: 'hazelnut-messenger.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkEX0BDjwn5_voxqKGO2UvQXB8ExSrIgA',
    appId: '1:383875206920:web:fd2f41ac6c2a99b13166bd',
    messagingSenderId: '383875206920',
    projectId: 'hazelnut-messenger',
    authDomain: 'hazelnut-messenger.firebaseapp.com',
    storageBucket: 'hazelnut-messenger.firebasestorage.app',
    measurementId: 'G-WCWYQN9PCW',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkEX0BDjwn5_voxqKGO2UvQXB8ExSrIgA',
    appId: '1:383875206920:web:dce6cad0aaaaae8f3166bd',
    messagingSenderId: '383875206920',
    projectId: 'hazelnut-messenger',
    authDomain: 'hazelnut-messenger.firebaseapp.com',
    storageBucket: 'hazelnut-messenger.firebasestorage.app',
    measurementId: 'G-4VNS1QWY53',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0vbBAzW1Fio4kPYT4auAXITPkjK8SGTA',
    appId: '1:383875206920:ios:1e1e3d9d38c1a5a23166bd',
    messagingSenderId: '383875206920',
    projectId: 'hazelnut-messenger',
    storageBucket: 'hazelnut-messenger.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0vbBAzW1Fio4kPYT4auAXITPkjK8SGTA',
    appId: '1:383875206920:ios:1e1e3d9d38c1a5a23166bd',
    messagingSenderId: '383875206920',
    projectId: 'hazelnut-messenger',
    storageBucket: 'hazelnut-messenger.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApp',
  );

}